name: FlyPerms
version: ${project.version}
main: com.benergy.flyperms.FlyPerms
authors: [ benwoo1110 ]
description: Toggle ability to fly based on permission
permissions:
  flyperms.allow:
    default: false
    description: Give players ability to fly!