name: FlyPerms
version: ${project.version}
api-version: 1.15
main: com.benergy.flyperms.FlyPerms
author: benwoo1110
description: Toggle ability to fly based on permission
commands:
  flyperms:
    description: Generic FlyPerms Command
    usage: /<command>
permissions:
  flyperms.allow:
    default: false
    description: Give players ability to fly!
