name: Report bug
description: Report a bug in FlyPerms
labels: 'bug'

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to report an FlyPerms bug! Fill out the form below to provide us with info to help fix the bug.

- type: dropdown
  attributes:
    label: Type of bug
    description: What type of bug is this? Choose all that apply.
    multiple: true
    options:
      - Performance issue or memory leak
      - Data loss
      - Exploit
      - Compatibility issue
      - Error in console
      - Other unexpected behaviour
  validations:
    required: true
    
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Also tell us, what did you expect to happen?
    placeholder: Tell us what you see!
    value: "A bug happened!"
  validations:
    required: true
