name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

    - name: Staging artifact
      run: mkdir staging && cp target/*.jar staging

    - name: Artifact output
      uses: actions/upload-artifact@v2
      with:
        name: FlyPerms-build
        path: staging
